# Generated by Django 5.2.17 on 2026-09-23 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HarvestJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_file", models.FileField(upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_urls", models.PositiveIntegerField(default=0)),
                ("skipped_rows", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UrlRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=64, null=True)),
                ("url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fetching", "Fetching"),
                            ("fetched", "Fetched"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("status_code", models.SmallIntegerField(blank=True, null=True)),
                ("raw_html", models.TextField(blank=True)),
                ("clean_text", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=512)),
                (
                    "fetch_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("requests", "requests"),
                            ("playwright", "playwright"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("indexed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_records",
                        to="harvest.harvestjob",
                    ),
                ),
            ],
            options={
                "unique_together": {("job", "url")},
            },
        ),
    ]
